# docker-compose-node.yml

version: "3"
services:
    proxy:
        image: httpd
        depends_on:
          - web
    web:
      image: node:8.12.0-jessie
      ports:
        - "8080:80"
      depends_on:
        - redis
    redis:
      image: redis